### ISSUE TITLE
update on 7.1.2021 bricked my moto g7 plus

### ISSUE THREAD

**Issue by davewood** [LineageOS/android_device_motorola_lake#4]
the unusal thing with my setup is that my screen is broken and I use scrcpy (https://github.com/Genymobile/scrcpy) to access the phone. but unlike before the update, if I start scrcpy now the phone reboots and then I only see a very low resolution and the device doesnt register any user input.

```
/ # scrcpy
INFO: scrcpy 1.16 <https://github.com/Genymobile/scrcpy>
* daemon not running; starting now at tcp:5037
* daemon started successfully
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 6.9 MB/s (33622 bytes in 0.005s)
[server] INFO: Device: Motorola moto g(7) plus (Android 10)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 20.1.9 (git-53b2b224dc)
INFO: Trilinear filtering enabled
INFO: Initial texture: 536x960

[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:36)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:169)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:173)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:211)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:94)
        at com.genymobile.scrcpy.Controller.control(Controller.java:71)
        at com.genymobile.scrcpy.Server$2.run(Server.java:89)
        at java.lang.Thread.run(Thread.java:919)
Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:511)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:855)
        ... 9 more
```

```
adb devices
List of devices attached
ZY225FG4HQ      device
```

is there a way to fix this using only adb?

**Comment by davewood** [comment]
in case someone else is having the same problem -> https://forum.xda-developers.com/t/rom-official-lineageos-17-1-nightlies.4076569/page-15#post-84258093
